name: Python application

on:
  workflow_dispatch:
    inputs:
      chatgpt-api-key:
        description: 'chatgpt-api-key'
        required: false
        default: 'CHANGEME'
      gpt3-turbo:
        description: 'Use gpt-3-turbo model'
        required: false
        default: true
      gpt-4:
        description: 'Use gpt-4 model'
        required: false
        default: false  # Default to true to select gpt-4 if no other option is provided
      gpt-4-turbo:
        description: 'Use gpt-4-turbo model'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-latest
    environment: OPENAI_API_KEY
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        env:
          OPENAI_API_KEY: ${{github.event.inputs.chatgpt-api-key}}
          GPT_MODEL: ${{ github.event.inputs.gpt3-turbo && 'gpt3-turbo' || github.event.inputs.gpt-4 && 'gpt-4' || github.event.inputs.gpt-4-turbo && 'gpt-4-turbo'}}
        run: |
          pytest
          python -c 'import test_draftgpt; test_draftgpt.draft_gpt()'

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: report.txt
          path: report.txt

